name: Yest FE build

env:
  secret_keys: "ACR-PASSWORD DEV-MONGO-URI"

on:
  release:
    types: [published]

# Push 시 체크 필요 시
#  push:
#    branches: [ main ]

## 수동 실행
  workflow_call:
    inputs:
      TEST_STRING:
        required: true
        type: string
    outputs:
      TEST_STRING:
        description: "Output Keyvault Secret"
        value: ${{ inputs.TEST_STRING }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Print Array ENV
        id: output_test
        run: |
          echo "${{ inputs.TEST_STRING }}"
          test="${{ inputs.TEST_STRING }}"
